# Site Information
site_name: Managed Services KB
repo_url: https://github.com/orgs/rivcoit/teams/rcit-tsb-m365/repositories
copyright: Copyright &copy; 2025 RCIT

theme:
  name: null
  custom_dir: blackout_theme
  language: en

extra_css:
  - assets/css/main.css
  - assets/css/custom.css
extra_javascript:
  - assets/js/lunr.min.js
  - assets/js/search-worker.js
  - assets/js/search.js
  - assets/js/main.js

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang: en
  - glightbox
  - git-revision-date-localized:
      type: datetime

nav:
  - Managed Services: index.md
  - Enterprise Notifications:
    - Export a Wiki to OneNote: EnterpriseNotifications/Export a wiki to a OneNote notebook in Microsoft Teams.md
    - Wiki Changes: EnterpriseNotifications/Important Update Changes to Note-Taking (Wiki) in Microsoft Teams.md
  - Exchange:
    - General Information: Exchange.md
    - eDiscovery:
      - eDiscovery Litigation: Exchange/eDiscoveryLitigation.md
      - Email Removal Requests: Exchange/mailremovaldefender.md
    - Mailboxes:
      - Creating User Email: Exchange/RemoteEnableUser.md
      - Message Trace: Exchange/MessageTrace.md
      - SMTP to SharedMailbox: Exchange/scan2email.md
    - Misc.:
      - 3rd Party:
        - TangoReserve: Exchange/3rdParty/TangoReserve/TRSetupChecklist.md
      - Help Desk Support: Exchange/Help Desk Support for Outlook.md
      - Next Request - PRAs: Exchange/NextRequest-PublicRecordsRequests.md
      - Role Clarification: Exchange/Role Clarification for M365 Services and Help Desk.md
    - Server:
      - Edge Subscription: Exchange/Server 2016/Create New Edge Subscription.md
      - Maintenance Mode: Exchange/Exchange 2016 server (Non-DAG Setup) maintenance mode.md
    - User Documentation:
      - Calendar Management: Exchange/UserDocumentation/M365-ExchangeOnline-UserCalendarManagement.md
      - Distribution Group Management: Exchange/UserDocumentation/M365-ExchangeOnline Distribution Group Management (EndUser).md
      - Distribution Group Types: Exchange/UserDocumentation/M365-ExchangeOnline Distribution Group Types.md
      - ServiceNow Request Guidelines: Exchange/UserDocumentation/M365-ExchangeOnline ServiceNow Request Submission Guidelines for Microsoft 365 Exchange Online Resource Access.md
      - Updating Auto-Reply: Exchange/UserDocumentation/M365-ExchangeOnline Autoreply for Shared Mailboxes.md
  - GitHub:
    - Actions:
      - Automations: GitHub/ActionsAutomations.md
    - Onboarding: GitHub/Onboarding.md
  - M365:
    - General Information: M365.md
    - Bots: M365/Framework-BotApproval-M365.md
    - Bookings: M365/Bookings/BookingsGovernance.md
    - Licensing:
      - General Information: M365/Licensing.md
      - Licensing Groups: M365/LicenseGroups.md
    - Misc:
      - Calendar Options: M365/CalendarOptionsinM365.md
    - Power BI: 
      - Publish to Web: M365/PowerBI/PublishtoWebGuidelines.md
      - Data Gateway Cluster Server Management:  
        - Updating the Data Gateway Cluster: M365/PowerBI/datagateways/patching-clustered-gateways.md
        - Additional Applications: M365/PowerBI/datagateways/gateway-additional-applications.md
  - Misc:
    - Syncs: Misc/Syncs.md
#  - Sharepoint: Sharepoint.md
  - Teams:
    - General Information: Teams.md
    - Device Provisioning: Teams/DeviceProvisioning.md
    - Device Management: Teams/DeviceManagement.md
    - Policies:
      - Recording: Teams/Policies/Recording.md
    - Troubleshooting:
      - Unblock Users: Teams/Troubleshooting/UnblockUser.md
  - Web Server Support:
    - General: WebServerSupport.md
    - FTP: 
      - GENERAL: WebServerSupport/FTP/general.md
      - CERBERUS:
        - Application Update: WebServerSupport/FTP/docs/Cerberus-ApplicationUpdate.md
        - FTP Group Creation: WebServerSupport/FTP/docs/Cerberus-FTPGroupCreation.md
    - Servers:
      - IIS:
        - RIVCO:
          - RCIT-16WEB01: WebServerSupport/IIS/RIVCOCA/RCIT-16WEB01.md
          - RCIT-16WEB01T: WebServerSupport/IIS/RIVCOCA/RCIT-16WEB01T.md
        - TZONE:
          - TZVM101: WebServerSupport/IIS/TZONE/TZVM101.md
          - TZVM102: WebServerSupport/IIS/TZONE/TZVM102.md
          - TZVM103: WebServerSupport/IIS/TZONE/TZVM103.md
          - TZVM104: WebServerSupport/IIS/TZONE/TZVM104.md
          - TZVM105: WebServerSupport/IIS/TZONE/TZVM105.md
          - TZVM106: WebServerSupport/IIS/TZONE/TZVM106.md
