site_name: Managed Services KB
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.follow
   # - toc.integrate
    - navigation.top
   # - navigation.tabs
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Light mode
      primary: cyan
      accent: deep orange
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark mode
      primary: cyan
      accent: deep orange
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition    
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
repo_url: https://github.com/orgs/rivcoit/teams/rcit-tsb-m365/repositories
plugins:
  - search: # necessary for search to work
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - glightbox
  - git-revision-date-localized:
      type: datetime
nav:
  - Managed Services: index.md
  - Enterprise Notifications:
    - Export a Wiki to OneNote: EnterpriseNotifications/Export a wiki to a OneNote notebook in Microsoft Teams.md
    - Wiki Changes: EnterpriseNotifications/Important Update Changes to Note-Taking (Wiki) in Microsoft Teams.md
  - Exchange: 
    - General Information: Exchange.md
    - eDiscovery:
      - eDiscovery Litigation: Exchange/eDiscoveryLitigation.md
      - Email Removal Requests: Exchange/mailremoval.md
    - Mailboxes:
      - Creating User Email: Exchange/RemoteEnableUser.md
      - Message Trace: Exchange/MessageTrace.md
      - SMTP to SharedMailbox: Exchange/scan2email.md
    - Misc.:
      - Help Desk Support: Exchange/Help Desk Support for Outlook.md
      - Role Clarification: Exchange/Role Clarification for M365 Services and Help Desk.md
    - Server:
      - Edge Subscription: Exchange/Server 2016/Create New Edge Subscription.md
      - Maintenance Mode: Exchange/Exchange 2016 server (Non-DAG Setup) maintenance mode.md
    - User Documentation:
      - Distribution Group Management: Exchange/UserDocumentation/M365-ExchangeOnline Distribution Group Management (EndUser).md
      - Distribution Group Types: Exchange/UserDocumentation/M365-ExchangeOnline Distribution Group Types.md
      - ServiceNow Request Guidelines: Exchange/UserDocumentation/M365-ExchangeOnline ServiceNow Request Submission Guidelines for Microsoft 365 Exchange Online Resource Access.md
      - Updating Auto-Reply: Exchange/UserDocumentation/M365-ExchangeOnline Autoreply for Shared Mailboxes.md
  - M365: 
    - General Information: M365.md
    - Bots: M365/Framework-BotApproval-M365.md
    - Licensing: M365/Licensing.md
    - Misc:
      - Calendar Options: M365/CalendarOptionsinM365.md
  - Misc:
    - Syncs: Misc/Syncs.md
  - Sharepoint: Sharepoint.md
  - Teams: 
    - General Information: Teams.md
    - Device Provisioning: Teams/DeviceProvisioning.md
    - Device Management: Teams/DeviceManagement.md
    - Troubleshooting:
      - Unblock Users: Teams/Troubleshooting/UnblockUser.md
    - More Things: 
      - Also Things: Teams/MoreThings.md

